(define (domain my_domain)
    (:requirements :strips :typing)
    (:types t1 t2)
    (:constants a b c - t1)
    (:predicates (p1 ?x - t1 ?y - t1 ?z - t1)  (p2 ?x - t1 ?y - t1))
    (:action a1
        :parameters (?x - t1 ?y - t1 ?z - t1)
        :precondition (and (p1 ?x ?y ?z) (p2 ?y ?z))
        :effect (p2 ?y ?z)
    )
)